### ISSUE TITLE
prompts for sudo password then hangs

### ISSUE THREAD

**Issue by sundeer** [neillturner/kitchen-ssh#1]
Running this...

```
$ bundle exec kitchen converge
-----> Starting Kitchen (v1.2.1)
-----> Creating <default-osx>...
       Kitchen-ssh does not start your server '192.168.1.118' but will look for an ssh connection with user 'rs'
       Kitchen-ssh found ssh ready on host '192.168.1.118' with user 'rs'

       Finished creating <default-osx> (0m0.01s).
-----> Converging <default-osx>...
       Preparing files for transfer
       Resolving cookbook dependencies with Berkshelf 3.1.5...
       Removing non-cookbook files before transfer
Password:
```

...throws up the sudo password prompt. Then, after entering remote password, nothing. It just hangs until I clt-c out. If I edit the target sudoers file and allow no passwords for all sudoers, it bypasses the sudo password prompt and behaves as expected.

Here'e my .kitchen.yml

```

---
driver:
  name: ssh
  hostname: 192.168.1.118
  username: rs
  password: mypassword
  sudo: yes
  require_chef_omnibus: true

platforms:
  - name: osx

provisioner:
  name: chef_solo

suites:
  - name: default
    run_list:
      - recipe[osxpreferences::defaults]
    attributes:
```

I'm not sure if I'm using the sudo: paramerter correctly or not.
